import LayoutWithPanelBlock from "@/components/blocks/layout-with-panel.block";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const AdminLayout: React.FC<React.PropsWithChildren> = ({ children }) => {
  return <LayoutWithPanelBlock>{children}</LayoutWithPanelBlock>;
};

export default AdminLayout;
