import ControlPanelBlock from "@/components/blocks/control-panel.block";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const AdminLayout: React.FC<React.PropsWithChildren> = ({ children }) => {
  return (
    <div className="h-full flex flex-col">
      <div className="flex-1 overflow-auto">{children}</div>

      <ControlPanelBlock />
    </div>
  );
};

export default AdminLayout;
